package eu.antonkrug;

/**
 * This file is auto-generated by baking tools inside the ./bake folder. Do not
 * change directly! To alter values or add new enums, change ./bake/api.py and
 * then run ./bake/pre_make.sh This will ensure that all values are constant
 * between Java, Python and JavaScript and will resolve to same numeric values.
 * 
 * @author Anton Krug
 */

public enum API {
  //@ff  to turn off formating

  NOT_VALID(0),
  R_LOGIN(1),
